In [ ]:
- min

- max

- mean

- median

- mode

- variance

- covariance

- standard deviation

- corelation

- zscore

- minmaxscaler

In [1]:
import numpy as np

In [3]:
l=list(range(1,20))
np.random.randint(l)

array([ 0,  1,  1,  1,  4,  3,  3,  5,  7,  9, 10,  1,  2, 12,  7,  7,  8,
       11, 16], dtype=int32)

In [5]:
np.random.exponential(l)

array([ 1.70877253,  2.66549208,  2.69779032,  2.29424465,  4.86352488,
        1.07448057,  4.71905207,  5.03438227,  9.02407362,  2.84444631,
       10.90142571,  1.78352828,  2.43509679, 42.79799226,  7.35526297,
        7.65791014, 39.72947775, 15.80076421, 25.60291321])

In [6]:
np.max(l)

np.int64(19)

In [7]:
np.min(l)

np.int64(1)

In [8]:
np.mean(l)

np.float64(10.0)

In [12]:
np.modf(l)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19.]))

In [13]:
np.var(l)

np.float64(30.0)

In [14]:
np.cov(l) #covariance

array(31.66666667)

In [18]:
np.correlate()

TypeError: correlate() missing 1 required positional argument: 'v'

In [20]:
np.average(l)

np.float64(10.0)

In [19]:
np.std(l)

np.float64(5.477225575051661)

In [1]:
import numpy as np
l=[10,20,30,40,50,60,70,80,90,100]
arr1=np.array(l)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**min**

In [2]:
np.min(l)

np.int64(10)

**max**

In [3]:
np.max(l)

np.int64(100)

**count non zero**

In [5]:
np.count_nonzero(arr1)

10

**sum**

In [6]:
np.sum(l)

np.int64(550)

**mean**

In [7]:
np.mean(l)

np.float64(55.0)

In [8]:
Sum=np.sum(l)
count=np.count_nonzero(arr1)
Sum/count

np.float64(55.0)

In [ ]:
# step1: xi means array
# step2: xbar  means mean of array
# step3: cal xi-xbar in the form of array
#          arr2=arr1-mean
# step4: square the of xi-xbar
#           arr3=square(arr2)
# step5: nr=sum of square of xi-xbar
#         nr=sum(arr3)
# step6: nr/Count

In [9]:
print(arr1)
print(arr1-55)

[ 10  20  30  40  50  60  70  80  90 100]
[-45 -35 -25 -15  -5   5  15  25  35  45]


In [10]:
print(arr1)
print(arr1-55)
print(np.square(arr1-))

SyntaxError: invalid syntax (3948175712.py, line 3)

In [11]:
x_bar=np.mean(arr1)
arr2=arr1-x_bar
arr3=np.square(arr2)
Nr=np.sum(arr3)
N=np.count_nonzero(arr3)
Nr/N

np.float64(825.0)

In [12]:
arr1-np.mean(arr1)
np.square(arr1-np.mean(arr1))
np.sum(np.square(arr1-np.mean(arr1)))
(np.sum(np.square(arr1-np.mean(arr1))))/np.count_nonzero(arr1)

np.float64(825.0)

In [13]:
(np.sum(np.square(arr1-np.mean(arr1))))/np.count_nonzero(arr1)

np.float64(825.0)

**std**

In [14]:
arr2=arr1-np.mean(arr1)
arr3=np.square(arr2)
arr4=np.sum(arr3)
arr5=np.sqrt(arr4)
dr=np.count_nonzero(arr1)
arr5/dr

np.float64(9.082951062292475)

In [17]:
count=np.count_nonzero(arr1)
(np.sqrt(np.sum(np.square(arr1-np.mean(arr1))))count)/dr

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2831343102.py, line 2)

**covariance**

In [19]:
x=range(1,11)
y=range(100,110)
len(x),len(y)

(10, 10)

In [20]:
list(x),list(y)

([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [26]:
arr1=np.array(x)
arr1_mean=np.mean(arr1)
arr11=arr1-arr1_mean

arr2=np.array(y)
arr2_mean=np.mean(arr2)
arr22=arr2-arr2_mean

arr3=arr11*arr22

arr4=np.sum(arr3)

arr4/9

np.float64(9.166666666666666)

In [24]:
arr1=np.array(x)
arr2=np.array(y)

np.sum((arr1-np.mean(arr1))*(arr2-np.mean(arr2)))/9

np.float64(9.166666666666666)

**corelation coeeficaiant**

In [27]:
arr1=np.array(x)
arr1_mean=np.mean(arr1)
arr11=arr1-arr1_mean

arr2=np.array(y)
arr2_mean=np.mean(arr2)
arr22=arr2-arr2_mean

Nr=np.sum(arr11*arr22)

a=np.sum(np.square(arr11))
b=np.sum(np.square(arr22))
Dr=np.sqrt(a*b)

Nr/Dr

np.float64(1.0)

**euclidean distance**
<img src="https://cdn.hswstatic.com/gif/distance-formula.jpg" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 1600px; height: 151px; margin: 0px; width: 268px;" alt="Distance Formula: Finding the Distance Between Two Points ..." jsname="kn3ccd">

In [ ]:
x=(10,20)
y=(5,6)


In [31]:
arr1=np.array(x)


arr2=np.array(y)

arr3=(arr1-arr2)
arr4=np.square(arr3)
arr5=np.sum(arr4)
np.sqrt(arr5)

np.float64(14.866068747318506)

In [32]:
np.sqrt(np.sum(np.square(arr1 - arr2)))

np.float64(14.866068747318506)

In [33]:
from numpy.linalg import norm

In [35]:
x=(10,20)
y=(5,6)
arr1=np.array(x)
arr2=np.array(y)
norm(arr1-arr2)


np.float64(14.866068747318506)

**cosine similarity**

In [37]:
x=[1,2,3]
y=[4,5,6]
arr1=np.array(x)
arr2=np.array(y)
Nr=np.dot(arr1,arr2)
x1=norm(arr1)
x2=norm(arr2)
Dr=x1*x2
Nr/Dr

np.float64(0.9746318461970762)